inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config.ru
    - db/schema.rb
    - tmp/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
    - 'db/migrate/*.rb'

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_param
    - find_by_document

Rails/SaveBang:
  Enabled: true

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: "strict"

Style/DateTime:
  Enabled: true
