---
news_article: &news_article
  path_prefix: /government/news
  lead_image: true
  attachments: inline_file_only
  publishing_metadata:
    schema_name: news_article
    rendering_app: government-frontend
  contents:
    - title_and_base_path
    - summary
    - body
  tags:
    - primary_publishing_organisation
    - organisations
    - role_appointments
    - topical_events
    - world_locations

publication: &publication
  pre_release: true
  path_prefix: /government/publications
  lead_image: false
  attachments: featured
  publishing_metadata:
    schema_name: publication
    rendering_app: government-frontend
  contents:
    - title_and_base_path
    - summary
    - body
  tags:
    - primary_publishing_organisation
    - organisations
    - role_appointments
    - topical_events
    - world_locations

document_types:
  - id: correspondence
    <<: *publication
    label: Correspondence

  - id: corporate_report
    <<: *publication
    label: Corporate report

  - id: foi_release
    <<: *publication
    label: FOI Release

  - id: impact_assessment
    <<: *publication
    label: Impact assessement

  - id: independent_report
    <<: *publication
    label: Independent report

  - id: news_story
    <<: *news_article
    label: News story

  - id: policy_paper
    <<: *publication
    label: Policy paper

  - id: press_release
    <<: *news_article
    label: Press release

  - id: promotional
    <<: *publication
    label: Promotional material

  - id: research
    <<: *publication
    label: Research and analysis

  - id: transparency
    <<: *publication
    label: Transparency
