---
- id: news_story
  label: News story
  description: "News written for GOV.UK which users need, can act on, and cannot get from other sources."
  path_prefix: /government/news
  images: true
  check_path_conflict: true
  publishing_metadata:
    schema_name: news_article
    rendering_app: government-frontend
  contents:
    - id: body
      label: Body
      type: govspeak
  tags:
    - id: primary_publishing_organisation
      label: Primary organisation
      type: single_tag
      document_type: organisation
      hint: The organisation responsible for publishing and maintaining this content.
    - id: organisations
      label: Organisations
      type: multi_tag
      document_type: organisation
      hint: Tag organisations associated with this content.
    - id: role_appointments
      label: Ministers and government appointments
      type: multi_tag
      document_type: role_appointment
      hint: Tag people who are directly involved.
    - id: topical_events
      label: Topical events
      type: multi_tag
      document_type: topical_event
      hint: Tag major events this content is related to. For example, summits or budgets.
    - id: world_locations
      label: World locations
      type: multi_tag
      document_type: world_location
      hint: Tag locations this content is about. If it only relates to the UK you don’t need to use this tag.

- id: press_release
  label: Press release
  description: "Unedited press releases as sent to the media, and official statements from the organisation."
  path_prefix: /government/news
  images: true
  check_path_conflict: true
  publishing_metadata:
    schema_name: news_article
    rendering_app: government-frontend
  contents:
    - id: body
      label: Body
      type: govspeak
  tags:
    - id: primary_publishing_organisation
      label: Primary organisation
      type: single_tag
      document_type: organisation
      hint: The organisation responsible for publishing and maintaining this content.
    - id: organisations
      label: Organisations
      type: multi_tag
      document_type: organisation
      hint: Tag organisations associated with this content.
    - id: role_appointments
      label: Ministers and government appointments
      type: multi_tag
      document_type: role_appointment
      hint: Tag people who are directly involved.
    - id: topical_events
      label: Topical events
      type: multi_tag
      document_type: topical_event
      hint: Tag major events this content is related to. For example, summits or budgets.
    - id: world_locations
      label: World locations
      type: multi_tag
      document_type: world_location
      hint: Tag locations this content is about. If it only relates to the UK you don’t need to use this tag.

- id: fatality_notice
  label: Fatality notice
  description: Initial fatality notices and subsequent obituaries of forces and MOD personnel
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/fatalities/new

- id: speech
  label: Speech
  description: Public speeches, written statements, or authored articles
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/speeches/new

- id: world_news_story
  label: World news story
  description: Announcements specific to one or more world location
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/news/new

- id: detailed_guide
  label: Detailed guide
  description: Detailed guidance for specialist users on the steps they need to take to complete a task
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/detailed-guides/new

- id: any-whitehall-publication
  label: Publication
  description: Standalone government documents that are issued and not usually updated
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/publications/new

- id: manual
  label: Manual
  description: Long and complex guidance broken into chapters and sub-sections for reference
  managed_elsewhere:
    hostname: manuals-publisher
    path: /

- id: any-mainstream-publication
  label: Mainstream guide
  description: Guidance for the general public on how to do something. Contact GDS to request changes.
  managed_elsewhere:
    hostname: support
    path: /content_change_request/new

- id: travel_advice
  label: Travel advice
  description: Travel advice by country including entry requirements and safety information
  managed_elsewhere:
    hostname: travel-advice-publisher
    path: /admin

- id: statistical-data-set
  label: Statistical data set
  description: Frequently updated (“live”) statistical data files.
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/statistical-data-sets/new

- id: case_study
  label: Case study
  description: Case studies show someone’s experience of a government process or policy problem
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/case-studies/new

- id: consultation
  label: Consultation
  description: A request for views or evidence on an issue
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/consultations/new
