development:
  secret_key_base: secret
  jwt_auth_secret: secret
  notify_api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>

test:
  secret_key_base: secret
  jwt_auth_secret: secret

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_auth_secret: <%= ENV['JWT_AUTH_SECRET'] %>
  notify_api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>
