development:
  secret_key_base: secret
  jwt_auth_secret: secret

test:
  secret_key_base: secret
  jwt_auth_secret: secret
  notify_non_production_allow_list: ["allowed@example.com"]

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_auth_secret: <%= ENV['JWT_AUTH_SECRET'] %>
  notify_api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>
  notify_non_production_allow_list: <%= ENV['GOVUK_NOTIFY_ALLOW_LIST'] %>
