development:
  secret_key_base: secret
  jwt_auth_secret: secret
  notify_api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>
  tagging_suggester_api_url: http://docker.for.mac.localhost:8000/create

test:
  secret_key_base: secret
  jwt_auth_secret: secret
  tagging_suggester_api_url: http://docker.for.mac.localhost:8000/create

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_auth_secret: <%= ENV['JWT_AUTH_SECRET'] %>
  notify_api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>
  tagging_suggester_api_url: <%= ENV['GOVUK_TAGGING_SUGGESTER_API_URL'] %>
