---
:verbose: false
:concurrency: 10
:max_retries: 0
:logfile: ./log/sidekiq.json.log
development:
  :logfile: null
:queues:
  - default
  - mailers
:schedule:
  asset_cleanup:
    interval: '30m'
    class: AssetCleanupJob
  populate_bulk_data:
    interval:
      - 15m
      - first_in: 0s
    class: PopulateBulkDataJob
