---
- id: news
  display_document_types:
    - news_story
    - press_release
    - fatality_notice
    - speech
    - world_news_story

- id: guidance
  display_document_types:
    - detailed_guide
    - any-whitehall-publication
    - manual
    - any-mainstream-publication
    - travel_advice

- id: transparency
  display_document_types:
    - any-whitehall-publication
    - statistical-data-set

- id: policy
  display_document_types:
    - case_study
    - consultation
    - any-whitehall-publication

- id: document-collection
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/collections/new

- id: corporate-information
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/organisations/government-digital-service/corporate_information_pages

- id: not-sure
  managed_elsewhere:
    path: /documents/publishing-guidance
